parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        # configure these for your database server
        driver:     'pdo_mysql'
        host:       '%databaseServer%'
        port:       '%databasePort%'
        dbname:     '%databaseName%'
        user:       '%databaseUsername%'
        password:   '%databasePassword%'
        server_version: '8.0'
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_general_ci
        options:
            prefix: '%databasePrefix%'
        mapping_types:
            enum: string
        # url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
            Comms:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Modules\Comms\Entity'
                prefix: 'App\Modules\Comms\Entity'
                alias: Comms
            Curriculum:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Modules\Curriculum\Entity'
                prefix: 'App\Modules\Curriculum\Entity'
                alias: Curriculum
            Enrolment:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Modules\Enrolment\Entity'
                prefix: 'App\Modules\Enrolment\Entity'
                alias: Enrolment
            Finance:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Modules\Finance\Entity'
                prefix: 'App\Modules\Finance\Entity'
                alias: Finance
            MarkBook:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Modules\MarkBook\Entity'
                prefix: 'App\Modules\MarkBook\Entity'
                alias: MarkBook
            People:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Modules\People\Entity'
                prefix: 'App\Modules\People\Entity'
                alias: People
            School:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Modules\School\Entity'
                prefix: 'App\Modules\School\Entity'
                alias: School
            Security:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Modules\Security\Entity'
                prefix: 'App\Modules\Security\Entity'
                alias: Security
            Staff:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Modules\Staff\Entity'
                prefix: 'App\Modules\Staff\Entity'
                alias: Staff
            Students:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Modules\Students\Entity'
                prefix: 'App\Modules\Students\Entity'
                alias: Students
            System:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Modules\System\Entity'
                prefix: 'App\Modules\System\Entity'
                alias: System
            Timetable:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Modules\Timetable\Entity'
                prefix: 'App\Modules\Timetable\Entity'
                alias: Timetable
        dql:
            string_functions:
                substring_index: App\Doctrine\SubstringIndexFunction
