services:
    Google_Client:
        class: Google_Client
        calls:
            - [setDeveloperKey, ['%google_api_key%']]
            - [setClientId, ['%google_client_id%']]
            - [setClientSecret, ['%google_client_secret%']]
