parameters:
    version: 0.0.00-dev
    systemRequirements:
        php: 7.3.0
        mysql: 5.6
        apache:
            - 'mod_rewrite'
        extensions:
            - 'gettext'
            - 'mbstring'
            - 'curl'
            - 'zip'
            - 'xml'
            - 'gd'
        settings:
            max_input_vars: [5000, '>=']
            max_file_uploads: [20, '>=']
            allow_url_fopen: [1, '==']
            register_globals: [0, '==']
