controllers:
    resource: ../../src/Controller/
    type: annotation
    schemes: [ 'https' ]

kernel:
    resource: ../../src/Kernel.php
    type: annotation
    schemes: [ 'https' ]

security_no_prefix:
    resource: ../../src/Modules/Security/ControllerNoPrefix/
    type: annotation
    schemes: [ 'https' ]

quoll_routes:
    resource: .
    type: quoll
    schemes: [ 'https' ]
