# config/packages/dev/web_profiler.yaml
web_profiler:
    toolbar:              '%kernel.debug%'
    intercept_redirects:  false
    excluded_ajax_paths:  '^/((index|app(_[\w]+)?)\.php/)?_wdt'

framework:
    profiler:
        enabled: '%kernel.debug%'