AUS:
    postcode:
        location: 'locality'
        validation: '#(^0[289][0-9]{2}$)|(^[1345689][0-9]{3}$)|(^2[0-8][0-9]{2}$)|(^290[0-9]$)|(^291[0-4]$)|(^7[0-4]{1}[0-9]{2}$)|(^7[8-9]{1}[0-9]{2}$)#'
        format:
            match: '#^([\d]{4})$#'
            template: '{1}'
    style: "propertyName\nflatUnit/streetNumber streetName\nlocality territory postCode\ncountry"
CAN:
    style: "propertyName\nflatUnit/streetNumber streetName\nlocality territory postCode\ncountry"
    postcode:
        location: 'street'
        validation: '#^[A-Z0-9]{3}[ ]{0,1}[A-Z0-9]{3}$#'
        format:
            match: '#(^[A-Z0-9]{3})([A-Z0-9]{3}$)#'
            template: '{1} {2}'
