<?php
/**
 * Created by PhpStorm.
 *
 * Quoll
 * (c) 2019 Craig Rayner <craig@craigrayner.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 * User: craig
 * Date: 4/09/2019
 * Time: 09:07
 */

namespace App\Modules\System\Form\Extension;

use Symfony\Component\Form\AbstractTypeExtension;
use Symfony\Component\Form\Extension\Core\Type\FormType;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\Form\FormView;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\OptionsResolver\OptionsResolver;

/**
 * Class SettingsExtension
 * @package App\Modules\System\Form\Extension
 */
class SettingsExtension extends AbstractTypeExtension
{
    /**
     * getExtendedTypes
     * @return array|iterable
     */
    public static function getExtendedTypes(): iterable
    {
        return [
            FormType::class,
        ];
    }

    /**
     * configureOptions
     * @param OptionsResolver $resolver
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(
            [
                'setting_form' => false,
            ]
        );

        $resolver->setAllowedTypes('setting_form', ['boolean']);
    }

    /**
     * finishView
     * @param FormView $view
     * @param FormInterface $form
     * @param array $options
     */
    public function finishView(FormView $view, FormInterface $form, array $options)
    {
        if ($options['setting_form']) {
            if ($view->vars['value'] !== $view->vars['data'] || $view->vars['value'] !== $options['data'])  {
                $view->vars['value'] = $options['data'];
                if ($view->vars['data'] instanceof File) {
                    $view->vars['value'] = $view->vars['data']->getRealPath();
                }
            }
        }
        parent::finishView($view, $form, $options); // TODO: Change the autogenerated stub
    }
}